### ISSUE TITLE
:bug: Code blocks don't render properly on light mode notes

### ISSUE THREAD

**Issue by trag1c** [Pincer-org/Pincer#293]
![image](https://user-images.githubusercontent.com/77130613/144768089-300e4234-a754-4bd7-8f6a-7ff68035a916.png)
![image](https://user-images.githubusercontent.com/77130613/144768076-c313925d-f219-4a58-b57c-c02dc54d3fe8.png)

**Comment by Endercheif** [comment]
Just fixed in https://github.com/Pincer-org/Pincer/commit/c16edb2c6df9c105a931fd73bd583ff2d02dbdeb

**Comment by Endercheif** [comment]
Currently waiting for RTD to recognize before closing this

**Comment by Endercheif** [comment]
Fixed

**Comment by trag1c** [comment]
Doesn't seem to be fixed though?

**Comment by Lunarmagpie** [comment]
Its fixed on my end. Make sure your browser isn't caching an older version of the docs.

**Comment by trag1c** [comment]
I have made sure it's not caching, I also have tried looking it up on incognito and on my phone + I asked my friend and my girlfriend to check and they were not able to see it properly as well so something's wrong :thinking:

**Comment by Lunarmagpie** [comment]
Works for me on Firefox and Chromium

**Comment by trag1c** [comment]
Also used this link (on Brave), friend used Firefox and girlfriend used Chrome I think

**Comment by Sigmanificient** [comment]
Firefox (v90) :check:
Chrome (v92) :check: 
Opera (v77) :check:

**Comment by trag1c** [comment]
What's the deal then :monocle_face:

**Comment by Endercheif** [comment]
Some debugging. 
1. Make sure you are on this link with light mode. https://docs.pincer.dev/en/latest/interactions.html
2. Hard refresh
3. Inspect Element and find the file called `custom.css`
4. Scroll to the bottom of that file
5. Look for `body[data-theme=light] .admonition.note .literal` It will look like how it is below
```css
.admonition.note {
 border-left-color:var(--blue-4);
 color:#fff
}
.admonition {
 background-color:var(--blue-6)
}
body[data-theme=light] .admonition.note .literal {
 color:initial
}
.sidebar-logo-container {
 animation:spinFade 1s cubic-bezier(.35,-.21,.04,1.52)
}
.sidebar-logo:hover {
 animation:Giggle 1s cubic-bezier(.35,-.21,.04,1.52) infinite
}
```

6. If it is missing, it is most probably a caching issue. If it is there then something is wrong.

**Comment by Endercheif** [comment]
Some debugging. 
1. Make sure you are on this link with light mode. https://docs.pincer.dev/en/latest/interactions.html
2. Hard refresh
3. Inspect Element and find the file called `custom.css`
4. Scroll to the bottom of that file
5. Look for `body[data-theme=light] .admonition.note .literal` It will look like how it is below
```css
.admonition.note {
 border-left-color:var(--blue-4);
 color:#fff
}
.admonition {
 background-color:var(--blue-6)
}
body[data-theme=light] .admonition.note .literal {
 color:initial
}
.sidebar-logo-container {
 animation:spinFade 1s cubic-bezier(.35,-.21,.04,1.52)
}
.sidebar-logo:hover {
 animation:Giggle 1s cubic-bezier(.35,-.21,.04,1.52) infinite
}
```

6. If it is missing, it is most probably a caching issue. If it is there then something is wrong.

**Comment by trag1c** [comment]
```css
/* note styling */
.admonition.note {
    border-left-color: var(--blue-4);
    color: #FFFFFF;
}
.admonition {
    background-color: var(--blue-6);
}
body[data-theme="light"] .admonition.note .literal {
 color: initial;
}

.sidebar-logo-container {
    animation: spinFade 1s cubic-bezier(.35,-0.21,.04,1.52);
}

.sidebar-logo:hover {
    animation: Giggle 1s cubic-bezier(.35,-0.21,.04,1.52) infinite;
}
```
It's here I guess
